M48
; DRILL file {KiCad 9.0.5} date 2026-01-12T16:44:47+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T16:44:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.550
%
G90
G05
T1
X126.175Y-142.4
X129.175Y-142.4
T2
X116.53Y-132.71
X177.47Y-60.48
T3
X116.53Y-69.13
X132.27Y-124.33
X161.73Y-68.86
X177.47Y-124.06
M30
